# Generated by Django 4.0.5 on 2022-07-24 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='salary',
            field=models.IntegerField(default=50000),
        ),
    ]
