# Generated by Django 4.0.5 on 2022-07-24 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_list', '0002_citizen_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
