# Generated by Django 4.0.5 on 2022-07-24 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_list', '0003_citizen_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='slug',
        ),
    ]
