# Generated by Django 4.0.5 on 2022-07-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_list', '0004_remove_citizen_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='status',
            field=models.IntegerField(default=3),
        ),
    ]
