# Generated by Django 4.0.5 on 2022-07-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen_list', '0005_citizen_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='boss',
            field=models.IntegerField(default=1),
        ),
    ]
